apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  namespace: elasticsearch
  name: example-es-cluster
spec:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
  cerebro:
    image: upmcenterprises/cerebro:0.6.8
  elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_1
  client-node-replicas: 3
  master-node-replicas: 2
  data-node-replicas: 3
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 10Gi
  java-options: "-Xms512m -Xmx512m"
  snapshot:
    scheduler-enabled: true
    type: gcs
    bucket-name: __SNAPSHOT_BUCKET__
    cron-schedule: "@every 2m"
    image: gcr.io/cloud-solutions-group/elasticsearch-cron:0.0.4
  storage:
    type: standard
    storage-class-provisioner: kubernetes.io/gce-pd
    volume-reclaim-policy: Delete
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 1024Mi
      cpu: '1'
