kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: data
  namespace: sock-shop-too
spec:
  podSelector:
    matchLabels:
      layer: data
  policyTypes:
    - Ingress
  ingress:
  - from:
      - podSelector:
          matchLabels:
            layer: service
      - podSelector:
          matchLabels:
            layer: shipping
    ports:
      - protocol: TCP
        port: 27017
      - protocol: TCP
        port: 3306
