apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: myapp-routerules-100p
spec:
  destination:
    name: myapp-gke-west-lb
    domain: svc.cluster.local
  route:
  - labels:
      stack: canary
    weight: 100
