kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: sock-shop-prod
  name: prod-viewer
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "deployments", "services", "configmaps"]
  verbs: ["get", "watch", "list"]
