
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: securedeployments.ctl.gcp.solutions
spec:
  group: ctl.gcp.solutions
  version: v1
  scope: Namespaced
  names:
    plural: securedeployments
    singular: securedeployment
    kind: SecureDeployment
    shortNames: ["sd", "securedeploy"]
---
apiVersion: metacontroller.k8s.io/v1alpha1
kind: CompositeController
metadata:
  name: securedeployment-controller
spec:
  generateSelector: true
  parentResource:
    apiVersion: ctl.gcp.solutions/v1
    resource: securedeployments
  childResources:
    - apiVersion: apps/v1
      resource: deployments
  hooks:
    sync:
      webhook:
        url: http://securedeployment-controller.metacontroller/
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: securedeployment-controller
  namespace: metacontroller
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxUnavailable: 1
  selector:
    matchLabels:
      app: securedeployment-controller
  template:
    metadata:
      labels:
        app: securedeployment-controller
    spec:
      terminationGracePeriodSeconds: 5
      containers:
      - name: controller
        image: gcr.io/__GOOGLE_PROJECT__/securedeployment-controller
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: securedeployment-controller
  namespace: metacontroller
spec:
  selector:
    app: securedeployment-controller
  ports:
  - port: 80
